using System;
using System.Reflection;
using System.Resources;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: GuidAttribute("458f202e-b233-42f0-999c-b3460f9cfcae")]
[assembly: ComVisibleAttribute(false)]
[assembly: CLSCompliantAttribute(true)]
[assembly: AssemblyConfigurationAttribute("debug,svn3919:3923M\r\n")]
[assembly: AssemblyCompanyAttribute("The jingxian Project")]
[assembly: AssemblyProductAttribute("jingxian")]
[assembly: AssemblyCopyrightAttribute("?2008 The jingxian Project")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyTitleAttribute("jingxian")]
[assembly: AssemblyDescriptionAttribute("DEBUG BUILD svn3919:3923M\r\n jingxian?- the plugin architecture")]
[assembly: NeutralResourcesLanguageAttribute("en-US")]

[assembly: AssemblyVersion("0.2.0.0")]
[assembly: InternalsVisibleTo(@"jingxian.core.TestSupport.simpl, PublicKeyToken=null")]
[assembly: InternalsVisibleTo(@"jingxian.core.runtime.Tests, PublicKeyToken=null")]
[assembly: InternalsVisibleTo(@"jingxian.core.runtime.castleIntegration.Tests, PublicKeyToken=null")]
[assembly: InternalsVisibleTo(@"jingxian.UI.Tests, PublicKeyToken=null")]
[assembly: InternalsVisibleTo(@"jingxian.UI.Workbench.Tests, PublicKeyToken=null")]
[assembly: InternalsVisibleTo(@"jingxian.UI.PropertyEditor.Tests, PublicKeyTokne=null")]
