//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3053
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace jingxian.core.utilities {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Error {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Error() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("jingxian.core.utilities.Error", typeof(Error).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot add argument &apos;{0}&apos; at position {1} (argument is allowed only once and was already given at position {2}). 的本地化字符串。
        /// </summary>
        internal static string ArgumentIsAllowedOnlyOnceAndWasAlreadyGiven {
            get {
                return ResourceManager.GetString("ArgumentIsAllowedOnlyOnceAndWasAlreadyGiven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Arguments 的本地化字符串。
        /// </summary>
        internal static string Arguments {
            get {
                return ResourceManager.GetString("Arguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot handle &apos;{0}&apos; at position {1} (arguments must have a minimum length of 2). 的本地化字符串。
        /// </summary>
        internal static string ArgumentsMustHaveMinimumLength {
            get {
                return ResourceManager.GetString("ArgumentsMustHaveMinimumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot handle &apos;{0}&apos; at position {1} (arguments must have a prefix of &apos;{2}&apos;, &apos;{3}&apos; or &apos;{4}&apos;). 的本地化字符串。
        /// </summary>
        internal static string ArgumentsMustHavePrefix {
            get {
                return ResourceManager.GetString("ArgumentsMustHavePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} of {1} given arguments successfully parsed. 的本地化字符串。
        /// </summary>
        internal static string ArgumentSuccessfullyParsed {
            get {
                return ResourceManager.GetString("ArgumentSuccessfullyParsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attribte &apos;{0}&apos; is required 的本地化字符串。
        /// </summary>
        internal static string AttribteIsRequired {
            get {
                return ResourceManager.GetString("AttribteIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Command line parse results 的本地化字符串。
        /// </summary>
        internal static string CommandLineParseResults {
            get {
                return ResourceManager.GetString("CommandLineParseResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default commands: 的本地化字符串。
        /// </summary>
        internal static string DefaultCommands {
            get {
                return ResourceManager.GetString("DefaultCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot handle &apos;{0}&apos; at position {1} (does not match any known argument). 的本地化字符串。
        /// </summary>
        internal static string DoNotMatchAnyArgument {
            get {
                return ResourceManager.GetString("DoNotMatchAnyArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 载入 schema 发生错误:  的本地化字符串。
        /// </summary>
        internal static string ErrorLoadingSchema {
            get {
                return ResourceManager.GetString("ErrorLoadingSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Errors 的本地化字符串。
        /// </summary>
        internal static string Errors {
            get {
                return ResourceManager.GetString("Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to parse argument at position {0} (argument is null or empty) 的本地化字符串。
        /// </summary>
        internal static string FailedToParseArgument {
            get {
                return ResourceManager.GetString("FailedToParseArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读命名空问 {1} 下的 {0} 必选节点时发生错误. 的本地化字符串。
        /// </summary>
        internal static string FailedToReadNonOptionalElement {
            get {
                return ResourceManager.GetString("FailedToReadNonOptionalElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 # Format: File Name (dll|exe), Version, Machine, PEKinds, Created 的本地化字符串。
        /// </summary>
        internal static string FileVersionFormat {
            get {
                return ResourceManager.GetString("FileVersionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 # File Version Info of {0} files in directory {1} 的本地化字符串。
        /// </summary>
        internal static string FileVersionInfoOfFilesInDirectory {
            get {
                return ResourceManager.GetString("FileVersionInfoOfFilesInDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ignoring argument &apos;{0}&apos; at position {1} (argument is allowed only once and was already given at position {2}). 的本地化字符串。
        /// </summary>
        internal static string IgnoringArgument {
            get {
                return ResourceManager.GetString("IgnoringArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Key {0} does not exist in this ObjectCache instance 的本地化字符串。
        /// </summary>
        internal static string KeyNotExistInObjectCache {
            get {
                return ResourceManager.GetString("KeyNotExistInObjectCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot get single argument (multiple arguments with identifier &apos;{0}&apos; found). 的本地化字符串。
        /// </summary>
        internal static string MultipleArgumentsWithIdentifierFound {
            get {
                return ResourceManager.GetString("MultipleArgumentsWithIdentifierFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No arguments given. 的本地化字符串。
        /// </summary>
        internal static string NoArgumentsGiven {
            get {
                return ResourceManager.GetString("NoArgumentsGiven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} parse errors detected. 的本地化字符串。
        /// </summary>
        internal static string ParseErrorDetected {
            get {
                return ResourceManager.GetString("ParseErrorDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必选属性 &apos;{0}&apos; 错误或为空. 的本地化字符串。
        /// </summary>
        internal static string RequiredAttributeIsMissingOrEmpty {
            get {
                return ResourceManager.GetString("RequiredAttributeIsMissingOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法取得参数 (&apos;{0}&apos; 不是一个有效的Identifier). 的本地化字符串。
        /// </summary>
        internal static string UknownIdentifier {
            get {
                return ResourceManager.GetString("UknownIdentifier", resourceCulture);
            }
        }
    }
}
