/* event-config.h
 *
 * This file was generated by autoconf when libevent was built, and post-
 * processed by Libevent so that its macros would have a uniform prefix.
 *
 * DO NOT EDIT THIS FILE.
 *
 * Do not rely on macros in this file existing in later versions.
 */
#ifndef _EVENT_CONFIG_H_
#define _EVENT_CONFIG_H_

#include "win32/config.h"

#endif //